#!/bin/sh

# Use neovim for vim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner" \
    mbsync="mbsync -c $HOME/.config/mbsync/mbsyncrc"

# Colorize commands when possible
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    ll="ls -lA -h --group-directories-first --color=auto" \
    la="ls -A -S1qX" \
    lh="ls -A" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    sp="stat -c '%a'" \
    ccat="highlight --out-format=ansi" \
    bat="bat -n"

# These common commands are just too long! abbreviate them
alias \
    ka="killall" \
    pk="pkill -9" \
    trx="transmission-remote -t all -S" \
    trg="transmission-remote -t all -s" \
    trd="transmission-remote -t all -r" \
    YT="youtube-viewer" \
    sdn="sudo shutdown -h now" \
    o="$FILE" \
    v="$EDITOR" \
    xbq="sudo xbps-query -Rs" \
    xbf="sudo xbps-query -f" \
    xbi="sudo xbps-install -Su" \
    xbr="sudo xbps-remove -R" \
    z="zathura"

# Make
alias \
    mki="make && sudo make install" \
    cb="make clean && rm -f blocks.h && git reset --hard origin/main" \
    cm="make clean && rm -f config.h && git reset --hard origin/main"

# Miscellaneous
alias \
    wph="curl wttr.in/San+Roque+San+Pedro+Laguna" \
    weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
    getpath="find -type f | fzf | sed 's/^..//' | tr -d '\n' | xclip -selection c" \
    fxp="chmod -R a=r,u+w,a+X" \
    cpat="echo $PATH | sed 's/:/\n/g' | sort | uniq -c" \
    df="df -h" \
    fn="fc-match -a | grep -i" \
    fne="fc-list : family | grep -i" \
    prm="shred -zvu -n 5" \
    xtar="tar xfv" \
    sysinfo="echo "" && sysinfo" \
    lfetch="echo "" && lfetch" \
    ifont="fc-cache -f -v" \
    gip="curl ipinfo.io/ip" \
    civ="convert +append" \
    cih="convert -append" \
    covidph="curl https://corona-stats.online/philippines" \
    covid="curl https://corona-stats.online/" \
    xrec="xmonad --recompile" \
    ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/sc.sh" \
