#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)";;
esac

. sb-theme
display "$(sensors | awk '/Core 0/ {print "CPU" $3}')"
