#!/bin/sh

case $BLOCK_BUTTON in
    1) setsid "$TERMINAL" -e newsboat ;;
esac

. sb-theme
display "$(cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ if($1>0) print "NEWS:" $1}')")"
