#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send \
"SA TIMEZONE $(TZ='Asia/Riyadh' date "+%I:%M%p")
PH TIMEZONE $(date "+%I:%M%p")"
esac

. sb-theme
display "$(TZ='Asia/Riyadh' date "+%I:%M%p") $(date "+%I:%M%p")"
