#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer -i 1 ;;
	5) pamixer -d 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

. sb-theme
if [ $(pamixer --get-mute) = true ]; then
	display "婢" "$color2"
	exit
fi

vol="$(pamixer --get-volume)"

if [ "$vol" -gt 70 ]; then
	icon=" "
elif [ "$vol" -gt 40 ]; then
	icon="墳 "
elif [ "$vol" -gt 10 ]; then
	icon=" "
else
	icon="奄 "
fi

display "$icon$vol%"
