#!/bin/sh

PREFIX='Updates:'

get_updates()
{
    if ! updates=$(xbps-install -Mun 2> /dev/null | wc -l ); then
        updates=0
    fi

    . sb-theme
    display "$(echo $PREFIX$updates)"
}

get_updates
