#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
xsetroot -cursor_name left_ptr &
xset s off -dpms &
xset r rate 300 50 &
xset m 2 0
setxkbmap -option caps:swapescape &
setbg &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          17

bspc config focused_border_color \#c0caf5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Screenkey manage=off
