#!/bin/sh
sxhkd &
$HOME/.local/bin/wm/polylaunch &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           30
bspc config top_padding          28

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=floating rectangle=1280x720+0+0
bspc rule -a firefox desktop='^2'
bspc rule -a Steam desktop='^5' state=floating rectangle=1376x625+0+0 follow=off
